"""add sheet_id to connection

Revision ID: 8343f0a42590
Revises: 18538cf69e48
Create Date: 2026-08-12 17:35:43.644783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8343f0a42590'
down_revision: Union[str, None] = '18538cf69e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_column('sheet_id')

    # ### end Alembic commands ###
