"""add channel_id to connection

Revision ID: b500fc8b9f02
Revises: 8343f0a42590
Create Date: 2026-08-13 13:07:31.959778
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b500fc8b9f02'
down_revision: Union[str, None] = '8343f0a42590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
